### PR TITLE
Added hero image

### PR DESCRIPTION
**Pull request by jfdesroches**
@rupakg would love your eyes on this please :)

## What did you implement:

Closes #XXXXX

## Todos:

- [x] Have you checked for typos and grammatical errors?
- [ ] If applicable, have you updated the [TOC](/guide/source/README.md)?

**Is this ready for review?:** [**Yes**/No]

### CODE REVIEW

**Comment by rupakg** [comment]
@jfdesroches Looking good. Later it will be cool to do a little animation with the compass/bolt moving and then settling down. :)

**Comment by jfdesroches** [comment]
Definitely :)

**Comment by rupakg** [comment]
@jfdesroches was thinking if we can remove the line and the text. I can then use a header in markdown and then position the image accordingly. I can play with spacing then. what do you say?

**Comment by jfdesroches** [comment]
Just uploaded a new one without the red line. If it didn't work, here's the original file
guide_repo

**Comment by rupakg** [comment]
@jfdesroches it did not get the new changes in the commit. Can you open the page again and add the new file?

**Pull request merged**
